import Head from 'next/head';
import styled from 'styled-components';
import { useState } from 'react';
import Property from '../components/Property';

const Wrapper = styled.div`
  display: grid;
  grid-template-rows: 50px auto 30px;
  flex-direction: column;
  width: 100vw;
  height: 100vh;
  padding: 0em 2rem;
`;

const Header = styled.header`
  display: flex;
  align-items: center;
  justify-content: space-between;
  h1 {
    font-size: 1.5rem;
  }
`;

const Main = styled.main`
  height: 100%;
  display: grid;
  grid-template-columns: 50% 50%;
  overflow: auto;

  & > div {
    overflow: hidden;

    display: flex;
    flex-direction: column;
    height: 100%;

    border: 1px solid #d1d5db;

    header {
      color: #fff;
      padding: 0.5rem;
      background: #6b7280;
    }

    main {
      flex: 1 1 auto;
    }
  }
`;

const Footer = styled.footer`
  display: flex;
  align-items: center;
  padding: 0.5rem 0;
`;

const TextArea = styled.textarea.attrs({ id: 'textArea', spellCheck: false })`
  resize: none;
  outline: none;
  border: none;
  width: 100%;
  height: 100%;
  padding: 1rem;
  font-family: inherit;
`;

const Input = styled.div``;

const Output = styled.div`
  margin-left: 10px;
  user-select: none;
  main {
    overflow: auto;
  }
`;

const PropertyWrapper = styled.div`
  width: 100%;
  height: 100%;
  padding: 1rem;
`;

const initialObject = { name: 'Gordon Freeman' };

export default function Home() {
  const [val, setVal] = useState(JSON.stringify(initialObject, null, 2));
  const [json, setJson] = useState(initialObject);
  const [filter, setFilter] = useState('');

  const change = (val) => {
    console.log('change');
    setVal(val);
    try {
      setJson(JSON.parse(val));
    } catch (e) {
      setJson({ error: e.toString() });
    }
  };

  const formatJSON = () => {
    try {
      console.log(typeof json);
      const parsed = JSON.parse(val);
      setVal(JSON.stringify(parsed, null, 2));
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <Wrapper>
      <Head>
        <title>JSONFiddle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h1>JSON Fiddle</h1>
      </Header>
      <Main>
        <Input>
          <header>
            <div onClick={formatJSON}>Format JSON</div>
          </header>
          <main>
            <TextArea value={val} onChange={(e) => change(e.target.value)} />
          </main>
        </Input>
        <Output>
          <header>Result</header>
          <main>
            <PropertyWrapper>
              <Property input={json} filter={filter} />
            </PropertyWrapper>
          </main>
        </Output>
      </Main>
      <Footer>Author: Johnny Blomgren & Tommy Wallberg</Footer>
    </Wrapper>
  );
}
